stages:
  - compile

compile:
  stage: compile
  image:
    name: registry.gitlab.com/kyokusei/ci_images/nim_gba:latest
  # before_script:
  #   - apt install -y texlive
  #   - apt install -y pandoc
  script:
    - make clean
    - make
    - printf "compilation succeded\n"
  artifacts:
    name: "$CI_PROJECT_NAME $CI_COMMIT_REF_NAME $CI_COMMIT_SHORT_SHA"
    paths:
      - ./*.gba
      # - ./guidebook.pdf
      - ./LICENSE