stages:
  - compile

compile:
  stage: compile
  image:
    name: registry.gitlab.com/kyokusei/ci_images/nim_gba:latest
  before_script:
    - apt install -y xxd
    - nimble install https://github.com/exelotl/nim-tonc.git
    - nimble install https://github.com/nim-lang/c2nim.git
  #   - apt install -y texlive
  #   - apt install -y pandoc
  script:
    - bash build.sh
    # - make clean
    # - nim c src/kyokusei_nim.nim
    # - make
    - printf "compilation succeded\n"
  artifacts:
    name: "$CI_PROJECT_NAME $CI_COMMIT_REF_NAME $CI_COMMIT_SHORT_SHA"
    paths:
      - ./*.gba
      # - ./guidebook.pdf
      - ./LICENSE